In [4]:
import numpy as np


In [5]:
x = [[1,3,2],[6,5,6],[0,46,5]]

In [6]:
y = np.array(x)

In [7]:
y

array([[ 1,  3,  2],
       [ 6,  5,  6],
       [ 0, 46,  5]])

In [2]:
import numpy as np

In [3]:
x = [1,2,3,4,5]

In [4]:
np.array(x)

array([1, 2, 3, 4, 5])

In [5]:
x

[1, 2, 3, 4, 5]

In [6]:
np.zeros((2,3)) +1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(10).reshape(2,5) #Reshape uses the multiple of available elements as input for convert 1d to specified dimension 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [11]:
np.random.randint(5)

4

In [12]:
np.argmax(x)

4

In [13]:
z = np.arange(0,10)

In [14]:
z[1:5]

array([1, 2, 3, 4])

In [15]:
z[-5:]

array([5, 6, 7, 8, 9])

In [20]:
q = np.arange(16).reshape(4,4)

In [21]:
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
q[0:2,1:3]

array([[1, 2],
       [5, 6]])